on:
  push:
    branches:    
    - 'master'
jobs:
  build_all:
    name: build_all
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: build
        # uses: docker://docker.pkg.github.com/cspotcode/docker-images/node-ci:latest
        # uses: cspotcode/docker-images/images/node-ci@master
        uses: cspotcode/docker-images/images/node-ci@node-ci-v2
        with:
          args: .github/workflows/continuous.sh
        env:
          GITHUB_TOKEN: '${{ github.token }}'
          GITHUB_REF: '${{ github.ref }}'
